# Site settings
title: Tome
author:
  name: Rudy Sargenti
  email: rsargenti99@gmail.com
description: "Tutorial site and future blog."

# Build settings
remote_theme: jekyll/minima
plugins:
  - jekyll-remote-theme
minima:
  skin: dark
