remote_theme: jekyll/minima
plugins:
- jekyll-remote-theme # add this line to the plugins list if you already have one

#theme: jekyll-theme-minimal
title: rssargenti's homepage
description: Testing config file
