# Site settings
title: Tome
author:
  name: Rudy Sargenti
  email: rsargenti99@gmail.com
description: "Tutorial site and future blog."

# Build settings
remote_theme: pages-themes/time-machine@v0.2.0
plugins:
  - jekyll-remote-theme
